[package]
name = "focus_flow"
version = "0.1.0"
description = "A cross-platform Focus Flow desktop app built with Rust/UI."
edition = "2024"

[workspace]

[features]
default = []
tauri = []

[lib]
name = "focus_flow"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
