[workspace]
resolver = "2"
members = ["app", "server", "crates/focus-flow-core"]

[workspace.dependencies]
leptos_ui = "0.3"
icons = { version = "0.18", features = ["leptos"] }
js-sys = "0.3"
send_wrapper = "0.6"


anyhow = "1"
axum = { version = "0.8", features = ["macros"] }
console_error_panic_hook = "0.1"
console_log = "1"
dotenv = "0.15"
http = "1"
leptos = { version = "0.8", features = ["nightly"] }
leptos_axum = "0.8"
leptos_meta = "0.8"
leptos_router = { version = "0.8", features = ["nightly"] }
log = "0.4"
tw_merge = { version = "0.1", features = ["variant", "debug"]}
strum = { version = "0.28", features = ["derive"] }
strum_macros = "0.28"
thiserror = "2"
tokio = { version = "1", features = ["rt-multi-thread"] }
tower = "0.5"
tower-http = { version = "0.7", features = ["fs"] }
wasm-bindgen = "0.2"
web-sys = { version = "0.3", features = ["MediaQueryList", "Storage", "Window"] }




[[workspace.metadata.leptos]]
name = "focus_flow"
bin-package = "server"
lib-package = "app"
site-root = "target/site"
assets-dir = "public"
site-pkg-dir = "pkg"
tailwind-input-file = "style/tailwind.css"
site-addr = "127.0.0.1:4317"
reload-port = 4318
browserquery = "defaults"
bin-features = []
bin-default-features = false
lib-features = ["hydrate"]
lib-default-features = false
